services:
  backend:
    build: ./backend
    ports:
      - 5050:5000

  postgres:
    image: postgres:14-alpine
    ports:
      - 6060:5432
    volumes:
      - ~/Development/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
      - POSTGRES_DB=master
